version: 2.1
orbs:
  cypress: cypress-io/cypress@3

executors:
  default:
    description: |
      Single Docker container used to run Cypress Tests
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    parameters:
      node-version:
        type: string
        default: "18.16.1"
        description: |
          The version of Node to run your tests with.

workflows:
  build:
    jobs:
      - cypress/run:
          executor:
            name: default
            node-version: "18.17.0"
          start-command: 'npm run start'
