version: 2.1
orbs:
  cypress: cypress-io/cypress@3

executors:
  docker:
  - image: cimg/node:node:18.17.0-browsers
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run start'

