version: 2.1
orbs:
  cypress: cypress-io/cypress@3

executors:
  default:
    docker:
      - image: cimg/node:18.17.0-browsers

jobs:
  cypress-run:
    executor: default
    steps:
      - cypress/run:
          start-command: 'npm run start'

workflows:
  version: 2
  build:
    jobs:
      - cypress-run
