version: 2.1
orbs:
  cypress: cypress-io/cypress@3

executors:
  default:
    description: |
      Single Docker container used to run Cypress Tests
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    parameters:
      node-version:
        default: 18.16.1
        description: |
          The version of Node to run your tests with.
        type: string

jobs:
  build:
    description: |
      A job to run Cypress end-to-end tests in your application.
    executor:
      name: default
      node-version: "18.17.0"  # 이 부분에서 Node.js 버전을 설정합니다.
    steps:
      - checkout
      - cypress/install
      - cypress/run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: Run Cypress Tests
          start-command: 'npm run start'
