version: 2.1
orbs:
  cypress: cypress-io/cypress@3

executors:
  default:
    description: |
      Single Docker container used to run Cypress Tests
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    parameters:
      node-version:
        default: 18.17.0
        description: |
          The version of Node to run your tests with.
        type: string

workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run start'

